<?php
/**
 * @file Compiler.php
 */

namespace clever_systems\mmm_builder;


use clever_systems\mmm_builder\RenderPhp\PhpFile;
use clever_systems\mmm_builder\RenderPhp\PhpLineComment;

class Compiler {
  /** @var Project */
  protected $project;

  /**
   * Compiler constructor.
   * @param Project $project
   */
  public function __construct(Project $project) {
    $this->project = $project;
  }

  public function compile() {
    $files = [];
    $files['sites/sites.php'] = $this->compileSitesPhp();
    $files['sites/all/drush/aliases.drushrc.php'] = $this->compileAliases();
    $files['../settings.baseurl.php'] = $this->compileBaseurls();
    $files['../settings.databases.php'] = $this->compileDbCredentials();
    $files['../settings.php'] = $this->scaffoldSettings();
    return $files;
  }

  public function compileAliases() {
    $php = (new PhpFile())
      ->addToHeader('// MMM autogenerated: Aliases')
      ->addToHeader('');

    foreach ($this->project->getInstallations() as $installation) {
      $installation->compileAliases($php);
    }
    return (string)$php;
  }

  public function compileSitesPhp() {
    $php = (new PhpFile())
      ->addToHeader('// MMM autogenerated: Sites')
      ->addToHeader('');

    foreach ($this->project->getInstallations() as $installation) {
      $installation->compileSitesPhp($php);
    }
    return (string)$php;
  }

  public function compileBaseUrls() {
    $php = (new PhpFile())
      ->addToHeader('// MMM autogenerated: Base Urls')
      ->addToHeader('use clever_systems\mmm_runtime\Runtime;')
      ->addToHeader('');

    foreach ($this->project->getInstallations() as $installation) {
      $installation->compileBaseUrls($php);
    }
    return (string)$php;
  }

  public function compileDbCredentials() {
    $php = (new PhpFile())
      ->addToHeader('// MMM autogenerated: DB Credentials')
      ->addToHeader('use clever_systems\mmm_runtime\Runtime;')
      ->addToHeader("\$host = rtrim(\$_SERVER['HTTP_HOST'], '.');")
      ->addToHeader('');

    foreach ($this->project->getInstallations() as $installation) {
      $installation->compileDbCredentials($php);
    }
    return (string)$php;
  }

  /**
   * @return string
   */
  protected static function scaffoldSettings() {
    $content = <<<EOD
<?php
// MMM settings file.
require '../vendor/autoload.php';
use clever_systems\mmm_runtime\Runtime;

require '../settings.baseurl.php';
require '../settings.databases.php';
Runtime::getEnvironment()->settings();
include '../settings.common.php';
include '../settings.local.php';

EOD;
    return $content;
  }

}